### ISSUE TITLE
[Help] User profile creation

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [julienlebren/flutter_firebase_phone_auth_riverpod#1]
Hey @julienlebren 
Thanks for your work, i will replace my implementation by yours; mine is messy :)

Could you share also how do you handle the user/profile creation (not the firebase auth one).

Im using `StartupPage` too, and im doing there kind of `getorCreateUser`; but it's an async process, and im getting some of intermediate black screen (while async request is running)...

Thank you,
Nelson

**Comment by julienlebren** [comment]
Hi,

I handle the user creation in Firestore with **Firebase Functions**.

Here is an extract from my code:

```typescript
import * as admin from 'firebase-admin';

const db = admin.firestore()

export async function onUserCreated(user: any): Promise<boolean> {
	if(typeof user.phoneNumber != "undefined") {
		const batch = db.batch()
		batch.set(db.collection("users").doc(user.uid), { 
			"phoneNumber": user.phoneNumber,
			"creationTime": new Date(user.metadata.creationTime),
		})

		batch.commit()
        return true
	}
    return false
}
```

Then in the app, I have a `StreamProvider` which watches the document on Firestore.
While it doesn't exist, it still display a progress indicator on the sign in verification page, so the process is toitally transparent for the user.

**Comment by Abacaxi-Nelson** [comment]
Thanks to share. 
I have quite similar process (waiting from a futureprovider responsible to create the user)

**Comment by julienlebren** [comment]
I am currently building an app which will be open-source and that will include the whole process, so stay tuned 😉
